version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_backend
    ports:
      - "8030:8080"
    environment:
      - FLASK_ENV=production